apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.4.2
  nodeSets:
  - name: default
    count: 5
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
